### ISSUE TITLE
FreeBSD build

### ISSUE THREAD

**Issue by adriaandegroot** [HamedMasafi/GitKlient#13]
> This is not an issue, this is a "thank you" and "well done!" message

GitKlient builds just fine on FreeBSD, with the one fix for SyntaxHighlighting applied (see issue #5 ). I like it! The algorithm for drawing branches and merges is neat, somewhat different from other graphical Git clients I've seen. And it can deal with the  convoluted 10000-commit history of Calamares without a hiccup. The 500000-commits of the FreeBSD ports collection are also loaded surprisingly quickly. Well done.

**Comment by adriaandegroot** [comment]
(Once there's a 0.3 release or so, I'll package GitKlient and put it in the FreeBSD ports collection)

**Comment by HamedMasafi** [comment]
Thank you very much for your kindness. Reported bugs have been fixed. There are more plans on my to-do list and I hope to release a great version of this tool soon.
