### ISSUE TITLE
Build error with SyntaxHighlighting

### ISSUE THREAD

**Issue by davidedmundson** [HamedMasafi/GitKlient#5]
https://github.com/HamedMasafi/GitKlient/blob/f94894e1e5e295e5eb50a0100502f8af3c10f24d/src/CMakeLists.txt#L119

Can you change to:

-    KF5SyntaxHighlighting
+    KF5::SyntaxHighlighting

Otherwise it doesn't build here.

**Comment by HamedMasafi** [comment]
Please tell me some information aboud your system:
os name and versiob
cmake --version
kf5 versions

**Comment by adriaandegroot** [comment]
For context, David is one of the upstream maintainers of the KDE Frameworks. Current KDE frameworks (5.95 at least, but from the date of the original report, 5.90 and later as well) deliver a `KF5SyntaxHighlightingTargets.cmake` that defines `KF5::SyntaxHighlighting` and no not-imported version of the target. It might have done so in the past.

Right now, for consistency with all the other frameworks listed in `src/CMakeLists.txt`, and to actually make it build (for me, with CMake 3.23, KDE Frameworks 5.96), it needs to be `KF5::SyntaxHighlighting`.

**Comment by HamedMasafi** [comment]
OK. I will change it as soon as possible

**Comment by HamedMasafi** [comment]
OK. I will change it as soon as possible

**Comment by adriaandegroot** [comment]
There's no `find_package()` corresponding to `KSyntaxHighlighting` (e.g. in the `find_package(KF5 ...)` part in the top-level CMakeLists, that might be a reason why it links weirdly.
