### ISSUE TITLE
.spec file

### ISSUE THREAD

**Issue by gryffus** [HamedMasafi/GitKlient#6]
Hello,

I am looking for packaging GitKlient for openSUSE and probably other distributions (yeah i know its in alpha/beta stage, but still, i am really amazed by the features, especially dolphin integration etc).
I have noticed, that you are providing .rpm packages. Can you please provide the .spec files used to build it, so I don't have to start from scratch?

Thanks!

**Comment by HamedMasafi** [comment]
Hello @gryffus 

There is no .spec file to generating rpm package! All is done by cpack

Also you can always download latest rpm package from release page 
For example: https://github.com/HamedMasafi/GitKlient/releases/tag/v0.1-alpha

**Comment by gryffus** [comment]
Yeah, i have tried the built package, but i am getting errors due to library versions mismatch, i guess:

```
May 26 10:31:13 gfs kernel: gitklient[12701]: segfault at 7ffea4859ff8 ip 00007f1c14c777b1 sp 00007ffea4859ff0 error 6 in libQt5Gui.so.5.15.2[7f1c14a17000+4ed000]
May 26 10:31:13 gfs kernel: Code: 04 48 89 47 04 0f b7 46 0c 66 89 47 0c e9 56 ff ff ff e8 62 34 da ff 66 90 53 48 89 fb 48 83 ec 10 64 48 8b 04 25 28 00 00 00 <48> 89 44 24 08 31 c0 e8 93 02 db ff 48 8b 44 24 08 64 48 2b 04 25
May 26 10:31:14 gfs kernel: gitklient[12707]: segfault at 7ffc2eedeff8 ip 00007f8806b417b1 sp 00007ffc2eedeff0 error 6 in libQt5Gui.so.5.15.2[7f88068e1000+4ed000]
May 26 10:31:14 gfs kernel: Code: 04 48 89 47 04 0f b7 46 0c 66 89 47 0c e9 56 ff ff ff e8 62 34 da ff 66 90 53 48 89 fb 48 83 ec 10 64 48 8b 04 25 28 00 00 00 <48> 89 44 24 08 31 c0 e8 93 02 db ff 48 8b 44 24 08 64 48 2b 04 25
May 26 10:31:18 gfs kernel: gitklient[12718]: segfault at 7ffe05390ffc ip 000055b49f3488ae sp 00007ffe05390ff0 error 6 in gitklient[55b49f2d1000+a7000]
May 26 10:31:18 gfs kernel: Code: 45 e8 c9 c3 f3 0f 1e fa 55 48 89 e5 48 89 7d f8 48 8b 45 f8 5d c3 f3 0f 1e fa 55 48 89 e5 48 83 ec 30 48 89 7d e8 48 89 75 e0 <89> 55 dc 64 48 8b 04 25 28 00 00 00 48 89 45 f8 31 c0 48 8b 45 e8
```
However, i would still like to have it in our official repositories. On Open Build Service, it is possible to build package for all distributions with sources from github automatically.

**Comment by HamedMasafi** [comment]
You mean openbuildservice.org?

it's looks like there is a problem in logging in.

**Login to profile is not available for employees yet.**

**Comment by HamedMasafi** [comment]
You mean openbuildservice.org? How can I use it to building my app? It's looks like closed for everyone use

**Comment by gryffus** [comment]
Yes, the software for that is Open Build Service and the source code is open: https://github.com/openSUSE/open-build-service

The instance hosted by SUSE is also free and available for everyone to use. It is building all *SUSE distributions and packages for them (and other distributions). This instance is hosted on https://build.opensuse.org/ . I, as a packager can create the packages for openSUSE for you and maybe for other distros too, if you are interested. I am also aiming for adding it to the official openSUSE KDE repositories (unstable).

I hope i will have some time for it on the weekend.

**Comment by HamedMasafi** [comment]
Sounds interesting, I would be grateful if you could do that
